### ISSUE TITLE
fwfh_text_style: Class 'FwfhTextStyle' has no instance getter '_fontFamily'.

### ISSUE THREAD

**Issue by Skyost** [daohoangson/flutter_widget_from_html#679]
## Steps to Reproduce

* Use the `fwfh_text_style` in a `Text` widget (which should be inside a `flutter_html_widget_core` widget).

<details>
  <summary>HTML</summary>

It's jsonified, but here is it :

```html
{"api":{"version":2,"latestVersion":2},"lesson":{"id":"suites","level":"terminale","title":"Chapitre I – Les suites","chapter":1,"specialty":false,"content":"/api/v2/terminale/suites/","comments":"/api/v2/terminale/suites/comments/","summary":"/api/v2/terminale/suites/summary/"},"difficulty":4,"pdf":"/pdf/lessons/terminale/suites.pdf","html":"<h2 id=\"définitions\">Définitions</h2>\n<h3 id=\"suites-numériques\">Suites numériques</h3>\n<p>Pour rappel, on appelle <strong>suite</strong> une fonction (et plus précisément application) de $\\mathbb{N}$ dans $\\mathbb{R}$ : cette fonction va prendre des éléments de l’ensemble de départ $\\mathbb{N}$ et va les amener dans l’ensemble d’arrivée $\\mathbb{R}$.</p>\n<div class=\"formula\">\n<h4>Définition</h4>\n<p>Il y a plusieurs manières de définir une suite :</p>\n<ul>\n<li><p><strong>Par récurrence :</strong> On donne le premier terme de la suite ainsi que le terme au rang $n+1$.</p></li>\n<li><p><strong>Par son terme général :</strong> On donne le $n$-ième terme de la suite en fonction de $n$.</p></li>\n</ul>\n</div>\n<p><strong>Attention !</strong> Bien que ces deux modes de génération soient les principaux, il en existe d’autres : algorithme, motifs géométriques, ...</p>\n<div class=\"tip\">\n<h4>Exemple</h4>\n<p>On définit les suites $(u_n)$ et $(v_n)$ ainsi :</p>\n<ul>\n<li><p>$u_n = n$ pour tout $n \\in \\mathbb{N}$ ($(u_n)$ est définie par son terme général).</p></li>\n<li><p>$(v_n) = \\begin{cases} v_0 = 0 \\\\ v_{n+1} = v_n + 1 \\text{ pour tout } n \\geq 1 \\end{cases}$ ($(v_n)$ est définie par récurrence).</p></li>\n</ul>\n<p>On remarque que bien que définies différemment, $(u_n)$ et $(v_n)$ sont égales.</p>\n</div>\n<h3 id=\"sens-de-variation\">Sens de variation</h3>\n<div class=\"formula\">\n<h4>Définition</h4>\n<p>Soit $(u_n)$ une suite.</p>\n<ul>\n<li><p>$(u_n)$ est <strong>croissante</strong> si on a $u_{n+1} \\geq u_n$ (ou $u_{n+1} - u_n \\geq 0$) pour tout $n \\in \\mathbb{N}$.</p></li>\n<li><p>$(u_n)$ est <strong>décroissante</strong> si on a $u_{n+1} \\leq u_n$ (ou $u_{n+1} - u_n \\leq 0$) pour tout $n \\in \\mathbb{N}$.</p></li>\n<li><p>$(u_n)$ est dite <strong>constante</strong> s’il existe $c \\in \\mathbb{R}$ tel que $u_n = c$ pour tout $n \\in \\mathbb{N}$.</p></li>\n</ul>\n</div>\n<p>Si une suite est croissante ou décroissante et ne change pas de variation, alors elle est dite <strong>monotone</strong>.</p>\n<h3 id=\"convergence-et-divergence\">Convergence et divergence</h3>\n<div class=\"formula\">\n<h4>Convergence</h4>\n<p>On dit qu’une suite $(u_n)$ <strong>converge</strong> vers un réel $\\ell$ quand $n$ tend vers $+\\infty$ si :</p>\n<p>Pour tout $\\epsilon &gt; 0$, l’intervalle ouvert $]\\ell-\\epsilon, \\ell+\\epsilon[$, contient tous les termes de la suite $(u_n)$ à partir d’un certain rang. On note alors : $\\lim_{n \\rightarrow +\\infty} u_n = \\ell$.</p>\n</div>\n<div class=\"tip\">\n\n<p>Cette définition est un peu abstraite mais elle signifie simplement que $u_n$ se rapproche autant que l’on veut de $\\ell$ pourvu que $n$ soit assez grand.</p>\n</div>\n<p><strong>Attention !</strong> Il est tout à fait possible que la suite $(u_n)$ converge vers un réel $\\ell$ mais ne soit jamais égal à $\\ell$.</p>\n<div class=\"formula\">\n<h4>Divergence vers $+\\infty$</h4>\n<p>On dit qu’une suite $(v_n)$ <strong>diverge</strong> vers $+\\infty$ quand $n$ tend vers $+\\infty$ si :</p>\n<p>Pour tout $A &gt; 0$, il existe un rang $N$ tel que pour tout $n \\geq N$, $v_n &gt; A$. On note alors : $\\lim_{n \\rightarrow +\\infty} u_n = +\\infty$.</p>\n</div>\n<p>Il existe une définition similaire pour la divergence vers $-\\infty$.</p>\n<div class=\"tip\">\n<h4>Divergence vers $-\\infty$</h4>\n<p>Dire que $(v_n)$ <strong>diverge</strong> vers $-\\infty$ signifie que :</p>\n<p>Pour tout $A &gt; 0$, il existe un rang $N$ tel que pour tout $n \\geq N$, $v_n &lt; -A$. On note alors : $\\lim_{n \\rightarrow +\\infty} u_n = -\\infty$.</p>\n</div>\n<div class=\"tip\">\n\n<p>À noter que l’on n’étudie les limites des <strong>suites</strong> que quand $n$ tend vers $+\\infty$, et qu’il est possible qu’une suite n’admette pas de limite. On dit alors que cette suite <strong>diverge</strong>. Par contre, si une suite converge vers une limite, alors cette limite est <strong>unique</strong>.</p>\n</div>\n<h2 id=\"calcul-de-limites\">Calcul de limites</h2>\n<h3 id=\"limites-de-suites-de-référence\">Limites de suites de référence</h3>\n<p>Nous allons donner quelques suites <q>classiques</q> avec leur limite en $+\\infty$ :</p>\n<div class=\"formula\">\n<h4>Limites de suites usuelles</h4>\n<table class=\"table table-bordered table-hover\">\n<thead>\n<tr class=\"header\">\n<th style=\"text-align: left;\"><strong>Suite</strong></th>\n<th style=\"text-align: left;\"><strong>Limite quand $n$ tend vers $+\\infty$</strong></th>\n</tr>\n</thead>\n<tbody>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">$(\\sqrt{n})$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">$(n)$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n</tr>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">$(n^k)$, pour $k \\in \\mathbb{N}^*$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">$\\left(\\frac{1}{\\sqrt{n}}\\right)$</td>\n<td style=\"text-align: left;\">$0$</td>\n</tr>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">$\\left(\\frac{1}{n}\\right)$</td>\n<td style=\"text-align: left;\">$0$</td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">$\\left(\\frac{1}{n^k}\\right)$, pour $k \\in \\mathbb{N}^*$</td>\n<td style=\"text-align: left;\">$0$</td>\n</tr>\n</tbody>\n</table>\n</div>\n<p>Nous allons désormais donner la limite d’une catégorie de suite très importante en mathématiques : celle des <strong>suites géométriques</strong>. Ainsi :</p>\n<div class=\"formula\">\n<h4>Limite de suites géométriques</h4>\n<p>Soit $(v_n)$ une suite définie pour tout $n \\in \\mathbb{N}$ par $v_n = q^n$ (où $q$ est un nombre réel). Alors, on peut donner la limite de la suite $(v_n)$ en fonction de $q$ :</p>\n<table class=\"table table-bordered table-hover\">\n<thead>\n<tr class=\"header\">\n<th style=\"text-align: left;\" colspan=\"5\"><strong>Limite d’une suite géométrique</strong></th>\n<th style=\"text-align: left;\"></th>\n</tr>\n</thead>\n<tbody>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Si on a...</td>\n<td style=\"text-align: left;\">$-1 &lt; q &lt; 1$</td>\n<td style=\"text-align: left;\">$1 &lt; q$</td>\n<td style=\"text-align: left;\">$q \\leq -1$</td>\n<td style=\"text-align: left;\">$q = 1$</td>\n<td style=\"text-align: left;\"></td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">Alors la suite $(v_n)$ a pour limite...</td>\n<td style=\"text-align: left;\">$0$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">Pas de limite</td>\n<td style=\"text-align: left;\">$1$</td>\n<td style=\"text-align: left;\"></td>\n</tr>\n</tbody>\n</table>\n</div>\n<div class=\"tip\">\n\n<p>Le réel $q$ est la <strong>raison</strong> de la suite : si $q &gt; 1$, $(v_n)$ est strictement croissante, si $0 &lt; q &lt; 1$, $(v_n)$ est strictement décroissante et si $q = 1$ ou $0$, $(v_n)$ est constante.</p>\n</div>\n<h3 id=\"opérations-sur-les-limites\">Opérations sur les limites</h3>\n<p>Dans tout ce qui suit, $(u_n)$ et $(v_n)$ sont deux suites. Ces tableaux sont à connaître et sont requis pour pouvoir travailler sur les limites.</p>\n<div class=\"formula\">\n<h4>Limite d’une somme</h4>\n<table class=\"table table-bordered table-hover\">\n<thead>\n<tr class=\"header\">\n<th style=\"text-align: left;\" colspan=\"7\"><strong>Limite d’une somme</strong></th>\n</tr>\n</thead>\n<tbody>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Si la limite de $(u_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">Et la limite de $(v_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell&#x27;$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n</tr>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Alors la limite de $(u_n + v_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell + \\ell&#x27;$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\"><strong>?</strong></td>\n</tr>\n</tbody>\n</table>\n</div>\n<div class=\"formula\">\n<h4>Limite d’un produit</h4>\n<table class=\"table table-bordered table-hover\">\n<thead>\n<tr class=\"header\">\n<th style=\"text-align: left;\" colspan=\"10\"><strong>Limite d’un produit</strong></th>\n</tr>\n</thead>\n<tbody>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Si la limite de $(u_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$\\ell &gt; 0$</td>\n<td style=\"text-align: left;\">$\\ell &gt; 0$</td>\n<td style=\"text-align: left;\">$\\ell &lt; 0$</td>\n<td style=\"text-align: left;\">$\\ell &lt; 0$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$0$</td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">Et la limite de $(v_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell&#x27;$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$\\pm \\infty$</td>\n</tr>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Alors la limite de $(u_n \\times v_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell \\times \\ell&#x27;$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\"><strong>?</strong></td>\n</tr>\n</tbody>\n</table>\n</div>\n<div class=\"formula\">\n<h4>Limite d’un quotient</h4>\n<table class=\"table table-bordered table-hover\">\n<thead>\n<tr class=\"header\">\n<th style=\"text-align: left;\" colspan=\"10\"><strong>Limite d’un quotient</strong></th>\n</tr>\n</thead>\n<tbody>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Si la limite de $(u_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$\\pm \\infty$</td>\n<td style=\"text-align: left;\">$\\ell$</td>\n<td style=\"text-align: left;\">$0$</td>\n</tr>\n<tr class=\"even\">\n<td style=\"text-align: left;\">Et la limite de $(v_n)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\ell&#x27; \\neq 0$</td>\n<td style=\"text-align: left;\">$\\pm \\infty$</td>\n<td style=\"text-align: left;\">$\\ell&#x27; &gt; 0$</td>\n<td style=\"text-align: left;\">$\\ell&#x27; &lt; 0$</td>\n<td style=\"text-align: left;\">$\\ell&#x27; &gt; 0$</td>\n<td style=\"text-align: left;\">$\\ell&#x27; &lt; 0$</td>\n<td style=\"text-align: left;\">$\\pm \\infty$</td>\n<td style=\"text-align: left;\">$0^+_-$</td>\n<td style=\"text-align: left;\">$0$</td>\n</tr>\n<tr class=\"odd\">\n<td style=\"text-align: left;\">Alors la limite de $\\left(\\frac{u_n}{v_n}\\right)$ quand $n$ tend vers $+\\infty$ est...</td>\n<td style=\"text-align: left;\">$\\displaystyle{\\frac{\\ell}{\\ell&#x27;}}$</td>\n<td style=\"text-align: left;\">$0$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$-\\infty$</td>\n<td style=\"text-align: left;\">$+\\infty$</td>\n<td style=\"text-align: left;\"><strong>?</strong></td>\n<td style=\"text-align: left;\">$\\pm \\infty$</td>\n<td style=\"text-align: left;\"><strong>?</strong></td>\n</tr>\n</tbody>\n</table>\n</div>\n<div class=\"tip\">\n<h4>Formes indéterminées</h4>\n<p>À noter qu’il n’existe que 4 formes indéterminées : <q>$+\\infty - \\infty$</q>, <q>$0 \\times \\pm \\infty$</q>, <q>$\\frac{\\pm \\infty}{\\pm \\infty}$</q> et <q>$\\frac{0}{0}$</q>.</p>\n</div>\n<h3 id=\"majoration-minoration-et-bornes\">Majoration, minoration et bornes</h3>\n<div class=\"formula\">\n<h4>Définition</h4>\n<p>Soient une suite $(u_n)$ et deux réels $m$ et $M$ :</p>\n<ul>\n<li><p>On dit que $m$ est un <strong>minorant</strong> de $(u_n)$ si pour tout $n$ : $u_n &gt; m$.</p></li>\n<li><p>On dit que $M$ est un <strong>majorant</strong> de $(u_n)$ si pour tout $n$ : $u_n &lt; M$.</p></li>\n<li><p>On dit que $(u_n)$ est <strong>bornée</strong> si elle est à la fois majorée et minorée.</p></li>\n</ul>\n</div>\n<div class=\"formula\">\n<h4>Théorème</h4>\n<ul>\n<li><p>Si $(u_n)$ est croissante et est majorée, alors elle est convergente. Si elle n’est pas majorée, $(u_n)$ diverge vers $+\\infty$.</p></li>\n<li><p>Si $(u_n)$ est décroissante et est minorée, alors elle est convergente. Si elle n’est pas minorée, $(u_n)$ diverge vers $-\\infty$.</p></li>\n</ul>\n</div>\n<div class=\"proof\">\n\n<p>Il faut savoir montrer que toute suite croissante et non majorée diverge vers $+\\infty$. C’est ce que nous allons faire ici. Soit donc $(u_n)$ une telle suite. Soit $A &gt; 0$, on cherche un rang $N$ tel que pour tout $n \\geq N$, $u_n &gt; A$.</p>\n<p>Or, comme $(u_n)$ est non majorée, il existe $N$ tel que $u_N &gt; A$. De plus, comme $(u_n)$ est croissante, alors $A &lt; u_N \\leq u_{N+1} \\leq u_{N+2} \\leq \\dots$</p>\n<p>Donc on a bien trouvé notre rang $N$ vérifiant la définition de la divergence vers $+\\infty$.</p>\n</div>\n<div class=\"tip\">\n\n<p>Toute suite convergente est également bornée.</p>\n</div>\n<h3 id=\"comparaisons-et-encadrements\">Comparaisons et encadrements</h3>\n<div class=\"formula\">\n<h4>Théorèmes de comparaison</h4>\n<p>Soient deux suites $(u_n)$ et $(v_n)$ telles que $u_n &lt; v_n$ à partir d’un certain rang $N$. On a :</p>\n<ul>\n<li><p>Si $\\lim\\limits_{n \\rightarrow +\\infty} u_n = +\\infty$, alors $\\lim\\limits_{n \\rightarrow +\\infty} v_n = +\\infty$.</p></li>\n<li><p>Si $\\lim\\limits_{n \\rightarrow +\\infty} v_n = -\\infty$, alors $\\lim\\limits_{n \\rightarrow +\\infty} u_n = -\\infty$.</p></li>\n<li><p>Si $\\lim\\limits_{n \\rightarrow +\\infty} u_n = \\ell$ et $\\lim\\limits_{n \\rightarrow +\\infty} v_n = \\ell&#x27;$ alors $\\ell &lt; \\ell&#x27;$.</p></li>\n</ul>\n</div>\n<div class=\"proof\">\n\n<p>Il peut être utile de savoir démontrer le premier point dans le cas $N = 0$ (les autres points se démontrent de manière semblable). Supposons $\\lim\\limits_{n \\rightarrow +\\infty} u_n = +\\infty$. Soit $A &gt; 0$, on cherche un rang $p$ tel que pour tout $n \\geq p$, $v_n &gt; A$.</p>\n<p>Comme $u_n$ diverge vers $+\\infty$, il existe un rang $q$ tel que pour tout $n \\geq q$, $u_n &gt; A$. Donc on a : $A &lt; u_q &lt; v_q$, mais aussi $A &lt; u_{q+1} &lt; v_{q+1}$, etc.</p>\n<p>Donc il suffit de poser $p = q$ et on a bien notre rang vérifiant la définition de la divergence vers $+\\infty$.</p>\n</div>\n<div class=\"formula\">\n<h4>Théorème des gendarmes</h4>\n<p>Soient trois suites $(u_n)$, $(v_n)$ et $(w_n)$. On suppose que $u_n &lt; v_n &lt; w_n$ à partir d’un certain rang et que $(u_n)$ et $(w_n)$ convergent vers le réel $\\ell$.</p>\n<p>Alors $\\lim\\limits_{n \\rightarrow +\\infty} v_n = \\ell$.</p>\n</div>\n<h2 id=\"raisonnement-par-récurrence\">Raisonnement par récurrence</h2>\n<p>Si on souhaite montrer qu’une propriété est vraie pour tout $n \\in \\mathbb{N}$ à partir d’un certain rang $p$, il est possible d’utiliser un type de raisonnement appelé <strong>raisonnement par récurrence</strong>.</p>\n<div class=\"formula\">\n<h4>Raisonnement par récurrence</h4>\n<p><strong>Initialisation :</strong> On teste la propriété au rang $p$. Si elle est vérifiée, on passe à l’étape suivante.</p>\n<p><strong>Hérédité :</strong> On suppose la propriété vraie à un rang $n \\geq p$. Puis on montre qu’elle reste vraie au rang $n+1$.</p>\n<p><strong>Conclusion :</strong> On explique que l’on vient de démontrer la propriété au rang $n+1$ et que comme celle-ci est initialisée et héréditaire, alors elle est vraie à partir du rang $p$.</p>\n</div>\n<div class=\"tip\">\n<h4>Exemple</h4>\n<p>Soit une suite $(u_n)$ définie par $(u_n) = \\begin{cases} u_0 = 4\\\\ u_{n+1} = \\frac{4u_n + 17}{u_n + 4}\\end{cases}$. On souhaite montrer que pour tout $n \\in \\mathbb{N}$, on a $4 \\leq u_n \\leq 5$.</p>\n<p>On note $\\mathcal{P}_n$ la propriété définie pour tout $n \\in \\mathbb{N}$ par $\\mathcal{P}_n$ : $4 \\leq u_n \\leq 5$.</p>\n<p>On constate que $u_{n+1} = \\frac{4u_n + 17}{u_n + 4} = \\frac{4(u_n + 4) + 1}{u_n + 4} = 4 + \\frac{1}{u_n + 4}$.</p>\n<p><strong>Initialisation :</strong> On teste la propriété au rang $0$ :</p>\n<p>$\\mathcal{P}_0$ : $4 \\leq u_0 \\leq 5 \\iff 4 \\leq 4 \\leq 5$. C’est vrai : la propriété est vraie au rang $0$.</p>\n<p><strong>Hérédité :</strong> Supposons la propriété vraie à un rang $n \\in \\mathbb{N}$ et vérifions qu’elle est vraie au rang $n+1$.</p>\n<p>D’après $\\mathcal{P}_n$ : $4 \\leq u_n \\leq 5$. Donc on a :</p>\n<p>$\\iff 4 \\leq u_n \\leq 5$</p>\n<p>$\\iff 4 + 4 \\leq u_n + 4 \\leq 5 + 4$</p>\n<p>$\\iff \\frac{1}{9} \\leq \\frac{1}{u_n + 4} \\leq \\frac{1}{8}$ (la fonction inverse est décroissante sur $\\mathbb{R}^+$ donc on change de sens l’inégalité)</p>\n<p>$\\iff 4 + \\frac{1}{9} \\leq 4 + \\frac{1}{u_n + 4} \\leq 4 + \\frac{1}{8}$</p>\n<p>Or $4 + \\frac{1}{9} \\approx 4.111 &gt; 4$ et $4 + \\frac{1}{8} = 4.125 &lt; 5$. On a donc bien :</p>\n<p>$4 \\leq u_{n+1} \\leq 5$</p>\n<p><strong>Conclusion :</strong> La propriété est initialisée au rang $0$ et est héréditaire. Ainsi, $\\mathcal{P}_n$ est vraie pour tout $n \\in \\mathbb{N}$.</p>\n</div>\n<div class=\"no-summary\">\n<p>Le raisonnement par récurrence est très utilisé en mathématiques et ne se limite pas qu’à l’étude des suites. On peut par exemple l’utiliser pour montrer l’<strong>inégalité de Bernoulli</strong>.</p>\n<div class=\"formula\">\n<h4>Inégalité de Bernoulli</h4>\n<p>$(1 + x)^n &gt; 1 + nx$ pour tout $n \\geq 2$ et tout $x \\in [-1, 0[ \\, \\cup \\, ]0, +\\infty[$.</p>\n</div>\n<div class=\"proof\">\n<h4>Inégalité de Bernoulli</h4>\n<p>Soit $x \\in [-1, 0[ \\, \\cup \\, ]0, +\\infty[$. On note $\\mathcal{P}_n$ la propriété définie pour tout $n \\geq 2$ par $\\mathcal{P}_n$ : $(1+x)^n &gt; 1+nx$. Montrons $\\mathcal{P}_n$ par récurrence.</p>\n<p><strong>Initialisation :</strong> On teste la propriété au rang $2$ :</p>\n<p>$\\mathcal{P}_2$: $(1+x)^2 = 1 + 2x + x^2 &gt; 1 + 2x$ (car $x^2 &gt; 0$).</p>\n<p>La propriété est vraie au rang $2$.</p>\n<p><strong>Hérédité :</strong> Supposons la propriété vraie à un rang $n \\geq 2$ et vérifions qu’elle est vraie au rang $n+1$.</p>\n<p>En multipliant les deux membres de l’inégalité de l’hypothèse de récurrence par $1+x \\geq 0$ (qui ne change donc pas le sens de l’inégalité), on obtient :</p>\n<p>$(1+x)^n (1+x) \\geq (1+nx)(1+x)$ $\\iff (1+x)^{n+1} \\geq 1 + (n+1)x + nx^2 &gt; 1 + (n+1)x$</p>\n<p><strong>Conclusion :</strong></p>\n<p>La propriété est initialisée au rang $2$ et est héréditaire. Ainsi, $\\mathcal{P}_n$ est vraie pour tout $n \\geq 2$.</p>\n</div>\n</div>\n","annals":[],"e3c":[]}
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
      HtmlWidget(
        data,
        baseUrl: Uri.parse(API.BASE_URL),
        buildAsync: buildAsync,
        customWidgetBuilder: buildCustomWidget,
        customStylesBuilder: (element) => buildCustomStyle(context, element),
        onLoadingBuilder: (context, element, progress) {
          String message = 'Rendu…';
          if (progress != null) {
            message += '\n' + progress.toString() + '%';
          }
          return CenteredCircularProgressIndicator(message: message);
        },
        onErrorBuilder: (context, element, error) {
          String title = error == null ? 'Erreur' : 'Erreur "${error.toString()}"';
          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 15),
            child: Center(
              child: Text(
                '$title. Veuillez réessayer plus tard.',
                textAlign: TextAlign.center,
                style: const TextStyle(fontStyle: FontStyle.italic),
              ),
            ),
          );
        },
        //rebuildTriggers: RebuildTriggers([data, buildCustomWidget, buildCustomStyle]),
        textStyle: textStyle,
        factoryBuilder: () => AppWidgetFactory(textStyle: textStyle),
      );
```
</details>

<details>
  <summary>Tesing environment</summary>

```
```
</details>

## Expected results

My HTML inside a beautiful `HtmlWidget` 😁

## Actual results

<img src="https://user-images.githubusercontent.com/3882599/145858873-3142dac9-0a1b-445b-a17e-2e16033057eb.png" height="500">

<details>

<summary>Stacktrace</summary>

```
The following NoSuchMethodError was thrown building Text("I – Définitions", inherit: true, color: Color(0xff23618a), family: FuturaBT, size: 38.4, dirty, dependencies: [DefaultTextStyle]):
Class 'FwfhTextStyle' has no instance getter '_fontFamily'.
Receiver: Instance of 'FwfhTextStyle'
Tried calling: _fontFamily

The relevant error-causing widget was: 
  Text Text:file:///D:/Hugo/Projets/Flutter/bacomathiques/lib/pages/html/widgets/title_widget.dart:93:11
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1      FwfhTextStyle._fontFamily (package:flutter/src/painting/text_style.dart:778:15)
#2      TextStyle.merge (package:flutter/src/painting/text_style.dart:1026:25)
#3      Text.build (package:flutter/src/widgets/text.dart:524:51)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (25 frames)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (45 frames)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#82     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#83     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:20)
#84     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#85     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#86     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#87     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962:59)
#88     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#89     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#90     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#91     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#92     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#94     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#95     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#97     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#98     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1935:12)
#99     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1881:20)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#110    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#116    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#118    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#120    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#121    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#122    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#123    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#125    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#126    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#128    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#129    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#130    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#132    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#133    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#134    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#135    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#136    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#137    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#138    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#139    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#140    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#141    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#142    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#146    _invoke (dart:ui/hooks.dart:150:10)
#147    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#148    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
```
</details>

**Comment by daohoangson** [comment]
You has a custom widget in `AppWidgetFactory` that builds `Text` with `FwfhTextStyle` directly?

**Comment by daohoangson** [comment]
You don't have to use `FwfhTextStyle` to build widgets, just use normal `TextStyle`.

Of course, using fwfh should work and this is a bug. I have released fwfh_text_style v2.7.1 to fix it.

**Comment by Skyost** [comment]
> You don't have to use `FwfhTextStyle` to build widgets, just use normal `TextStyle`.

Well, I had [this error](https://github.com/daohoangson/flutter_widget_from_html/blob/e0d6d99836b52c08c3130778bd9fcd3426242b22/packages/core/lib/src/data/text_style.dart#L63) :

`The text style should be modified by calling methods of the existing instance: apply(), copyWith() or merge().`

because my style was not a `FwfhTextStyle`.

**Comment by daohoangson** [comment]
You did use apply/copyWith/merge and that error still popped up? Can you share the code? That sounds a bug.

**Comment by Skyost** [comment]
> You did use apply/copyWith/merge and that error still popped up?

Nope.

> Can you share the code? That sounds a bug.

Well, the app is a bit complex so it's complicated to share all the source code. I'm gonna do my best ! (Keep in mind that I wasn't using `fwfh_text_style` before)

Here's the widget that I use to display HTML content :

<details>

<summary>AppHtmlWidget</summary>

```dart
/// Allows to display a HTML widget.
class AppHtmlWidget extends StatelessWidget {
  /// The HTML data.
  final String data;

  /// The text style.
  final TextStyle textStyle;

  /// Whether to build it async.
  final bool buildAsync;

  /// Creates a new app HTML widget instance.
  const AppHtmlWidget({
    required this.data,
    required this.textStyle,
    this.buildAsync = true,
  });

  @override
  Widget build(BuildContext context) => HtmlWidget(
        data,
        baseUrl: Uri.parse(API.BASE_URL),
        buildAsync: buildAsync,
        customWidgetBuilder: buildCustomWidget,
        customStylesBuilder: (element) => buildCustomStyle(context, element),
        onLoadingBuilder: (context, element, progress) {
          String message = 'Rendu…';
          if (progress != null) {
            message += '\n' + progress.toString() + '%';
          }
          return CenteredCircularProgressIndicator(message: message);
        },
        onErrorBuilder: (context, element, error) {
          String title = error == null ? 'Erreur' : 'Erreur "${error.toString()}"';
          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 15),
            child: Center(
              child: Text(
                '$title. Veuillez réessayer plus tard.',
                textAlign: TextAlign.center,
                style: const TextStyle(fontStyle: FontStyle.italic),
              ),
            ),
          );
        },
        //rebuildTriggers: RebuildTriggers([data, buildCustomWidget, buildCustomStyle]),
        textStyle: textStyle,
        factoryBuilder: () => AppWidgetFactory(textStyle: textStyle),
      );

  /// Builds the widget of an element.
  Widget? buildCustomWidget(dom.Element element) {
    if (element.attributes.containsKey('data-api-v2-geogebra-image') && element.attributes.containsKey('data-api-v2-geogebra-id')) {
      return RepresentationPreviewWidget(
        imageURL: element.attributes['data-api-v2-geogebra-image']!,
        geogebraId: element.attributes['data-api-v2-geogebra-id']!,
      );
    }

    return null;
  }

  /// Builds the style of an element.
  Map<String, String>? buildCustomStyle(BuildContext context, dom.Element element) {
    Map<String, String> style = {
      if (element.classes.contains('mb-0')) 'margin-bottom': '0',
      if (element.classes.contains('center')) 'text-align': 'center',
    };

    switch (element.localName) {
      case 'h2':
      case 'h3':
      case 'h4':
        return {
          'margin-top': '0',
          'padding-top': '0',
          'margin-bottom': '0',
          'padding-bottom': '0',
          ...style,
        };
      case 'p':
        return {
          'margin-top': '0',
          'padding-top': '0',
          ...style,
        };
      case 'ol':
        {
          return {
            'margin-top': '0',
            'margin-bottom': '0',
            'padding-left': '2em',
            ...style,
          };
        }
      case 'ul':
        return {
          'list-style-type': 'dash',
          'margin-top': '0',
          'margin-bottom': '0',
          'padding-left': '2em',
          ...style,
        };
      case 'li':
        return {
          'margin-bottom': '0.8em',
          ...style,
        };
      case 'table':
        AppTheme theme = context.resolveTheme(listen: false);
        return {
          'background-color': theme.brightness == Brightness.light ? 'white' : 'transparent',
          'border': '0.5px solid #cfcfcf',
          ...style,
        };
      case 'th':
        return {
          'padding': '10px',
          'border-top': '0.5px solid #cfcfcf',
          'border-right': '0.5px solid #cfcfcf',
          'border-left': '0.5px solid #cfcfcf',
          'border-bottom': '1px solid #cfcfcf',
          ...style,
        };
      case 'td':
        return {
          'padding': '10px',
          'border': '0.5px solid #cfcfcf',
          ...style,
        };
      case 'img':
        return {
          'max-height': '150px',
          ...style,
        };
    }

    return null;
  }
}
```

</details>

Here's my custom widget factory :

<details>

<summary>AppWidgetFactory</summary>

```dart
/// Allows to display custom widgets to the HTML content.
class AppWidgetFactory extends WidgetFactory with SvgFactory {
  /// The list view tag build op.
  BuildOp? lv;

  /// The "scroll to this" global key.
  GlobalKey? scrollToThisKey;

  /// The a tag build op.
  BuildOp? a;

  /// The math tag build op.
  BuildOp? math;

  /// The formula tag build op.
  BuildOp? formula;

  /// The tip tag build op.
  BuildOp? tip;

  /// The proof tag build op.
  BuildOp? proof;

  /// The H2 tag build op.
  BuildOp? h2;

  /// The H3 tag build op.
  BuildOp? h3;

  /// The H4 tag build op.
  BuildOp? h4;

  /// The text style.
  final TextStyle textStyle;

  /// Creates a new app widget factory instance.
  AppWidgetFactory({
    required this.textStyle,
  });

  @override
  void parse(BuildMetadata meta) {
    super.parse(meta);
    if (meta.element.localName == 'lv') {
      String? scrollTarget = meta.element.attributes['data-scroll-target'];
      lv ??= BuildOp(
        onChild: scrollTarget == null || scrollToThisKey != null
            ? null
            : (meta) {
          if (meta.element.id == scrollTarget) {
            scrollToThisKey = GlobalKey();
            meta.register(
              BuildOp(
                onWidgets: (meta, children) => [
                  ScrollToThis(scrollToThisKey!),
                  ...children,
                ],
              ),
            );
          }
        },
        onWidgets: (meta, children) => [
          ListViewWidget(
            scrollToThisKey: scrollToThisKey,
            children: children.toList(),
          ),
        ],
      );
      meta.register(lv!);
    } else if (meta.element.localName == 'a') {
      a ??= BuildOp(
        onTree: (meta, tree) => tree.add(
          WidgetBit.inline(
            tree,
            LinkWidget.fromElement(
              element: meta.element,
              fontSize: textStyle.fontSize!,
            ),
          ),
        ),
      );
      meta.register(a!);
    } else if (meta.element.localName == 'math') {
      math ??= BuildOp(
        onTree: (meta, tree) => tree.add(
          WidgetBit.inline(
            tree,
            MathWidget.fromElement(
              element: meta.element,
              textStyle: textStyle,
            ),
          ),
        ),
      );
      meta.register(math!);
    } else if (meta.element.classes.contains(Bubble.FORMULA.className)) {
      formula ??= _createBubbleBuildOp(Bubble.FORMULA, meta);
      meta.register(formula!);
    } else if (meta.element.classes.contains(Bubble.TIP.className)) {
      tip ??= _createBubbleBuildOp(Bubble.TIP, meta);
      meta.register(tip!);
    } else if (meta.element.classes.contains(Bubble.PROOF.className)) {
      proof ??= _createBubbleBuildOp(Bubble.PROOF, meta);
      meta.register(proof!);
    } else if (meta.element.localName == 'h2') {
      h2 ??= _createTitleBuildOp(meta);
      meta.register(h2!);
    } else if (meta.element.localName == 'h3') {
      h3 ??= _createTitleBuildOp(meta);
      meta.register(h3!);
    } else if (meta.element.localName == 'h4') {
      h4 ??= _createTitleBuildOp(meta);
      meta.register(h4!);
    }
  }

  @override
  String getListMarkerText(String type, int i) {
    if (type == 'dash') {
      return '— ';
    }
    return super.getListMarkerText(type, i);
  }

  /// Creates a title build op.
  BuildOp _createTitleBuildOp(BuildMetadata meta) => BuildOp(
        onTree: (meta, tree) => tree.add(
          WidgetBit.block(tree, TitleWidget.fromElement(element: meta.element)),
        ),
      );

  /// Creates a bubble build op.
  BuildOp _createBubbleBuildOp(Bubble bubble, BuildMetadata meta) => BuildOp(
        onChild: (meta) {
          if (meta.element.localName == 'h4' || meta.element.localName == 'a') {
            meta.element.attributes['data-parent-bubble'] = bubble.className;
          }
        },
        onWidgets: (meta, children) => [
          BubbleWidget.fromElement(
            element: meta.element,
            children: children.toList(),
          ),
        ],
      );
}
```

</details>

The error mainly occurs when there is a heading in my HTML. Headings are displayed using the following widget :

<details>

<summary>AppWidgetFactory</summary>

```dart
/// Allows to get the color according to the specified app theme.
typedef ColorGetter = Color? Function(AppTheme theme, dom.Element element);

/// Allows to display a title.
class TitleWidget extends StatelessWidget {
  /// The base size.
  static const int _BASE_SIZE = 16;

  /// The font size.
  final double fontSize;

  /// Returns the color of this title according to the provided theme.
  final ColorGetter? getColor;

  /// Returns the border bottom color of this title according to the provided theme.
  final ColorGetter? getBorderBottomColor;

  /// The DOM element.
  final dom.Element element;

  /// The container padding.
  final EdgeInsets? padding;

  /// The container margin.
  final EdgeInsets? margin;

  /// Creates a new headline 2 formatted title.
  const TitleWidget.h2({
    required this.element,
  })  : fontSize = 2.4 * _BASE_SIZE,
        getColor = _getH2Color,
        getBorderBottomColor = _getH2BorderBottomColor,
        padding = const EdgeInsets.only(bottom: 0.5 * _BASE_SIZE),
        margin = const EdgeInsets.only(bottom: 0.3 * _BASE_SIZE);

  /// Creates a new headline 3 formatted title.
  const TitleWidget.h3({
    required this.element,
  })  : fontSize = 1.75 * _BASE_SIZE,
        getColor = _getH3Color,
        getBorderBottomColor = null,
        padding = const EdgeInsets.only(bottom: 0.8 * _BASE_SIZE),
        margin = null;

  /// Creates a new headline 4 formatted title.
  TitleWidget.h4({
    required this.element,
  })  : fontSize = 1.25 * _BASE_SIZE,
        getColor = _getH4Color,
        getBorderBottomColor = null,
        padding = const EdgeInsets.only(bottom: 0.75 * _BASE_SIZE),
        margin = null;

  /// Creates a new title widget from the specified element.
  factory TitleWidget.fromElement({
    required dom.Element element,
  }) {
    switch (element.localName) {
      case 'h3':
        return TitleWidget.h3(element: element);
      case 'h4':
        return TitleWidget.h4(element: element);
      default:
        return TitleWidget.h2(element: element);
    }
  }

  @override
  Widget build(BuildContext context) {
    AppTheme theme = context.resolveTheme();
    TextStyle textStyle = FwfhTextStyle.from(
      TextStyle(
        fontFamily: 'FuturaBT',
        fontSize: fontSize,
        color: (getColor == null ? theme.textColor : getColor!(theme, element)) ?? theme.textColor,
      ),
    );

    Widget child = RegExp(r'<\/?[a-z][\s\S]*>', caseSensitive: false).hasMatch(element.innerHtml)
        ? AppHtmlWidget(
            data: element.innerHtml,
            buildAsync: false,
            textStyle: textStyle,
          )
        : Text(
            element.innerHtml,
            style: textStyle,
          );

    Color? borderBottomColor = getBorderBottomColor == null ? null : getBorderBottomColor!(theme, element);
    return Container(
      decoration: borderBottomColor == null
          ? null
          : BoxDecoration(
              border: Border(
                bottom: BorderSide(
                  color: borderBottomColor,
                ),
              ),
            ),
      width: MediaQuery.of(context).size.width,
      margin: margin,
      padding: padding,
      child: child,
    );
  }

  /// Returns the color of the headline 2 according to the specified theme.
  static Color? _getH2Color(AppTheme theme, dom.Element element) => theme.h2Color;

  /// Returns the border bottom color of the headline 2 according to the specified theme.
  static Color? _getH2BorderBottomColor(AppTheme theme, dom.Element element) => theme.hrColor;

  /// Returns the color of the headline 3 according to the specified theme.
  static Color? _getH3Color(AppTheme theme, dom.Element element) => theme.h3Color;

  /// Returns the color of the headline 4 according to the specified theme.
  static Color? _getH4Color(AppTheme theme, dom.Element element) {
    Bubble bubble = BubbleUtils.getByClassName(element.attributes['data-parent-bubble']);
    return theme.bubbleThemes[bubble]?.leftBorderColor;
  }
}
```

</details>

I leave you a link to the [Github repository](https://github.com/Skyost/Bacomathiques/tree/app) (see the `lib/pages/html/` folder).

**Comment by Skyost** [comment]
I'm still getting the same error with the new version btw.

<details>

<summary>Stacktrace</summary>

```
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building Text("I – Définitions", inherit: true, color: Color(0xff23618a), family: FuturaBT, size: 38.4, dirty, dependencies: [DefaultTextStyle]):
Class 'FwfhTextStyle' has no instance getter '_fontFamily'.
Receiver: Instance of 'FwfhTextStyle'
Tried calling: _fontFamily

The relevant error-causing widget was: 
  Text Text:file:///D:/Hugo/Projets/Flutter/bacomathiques/lib/pages/html/widgets/title_widget.dart:93:11
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1      FwfhTextStyle._fontFamily (package:flutter/src/painting/text_style.dart:778:15)
#2      TextStyle.merge (package:flutter/src/painting/text_style.dart:1026:25)
#3      Text.build (package:flutter/src/widgets/text.dart:524:51)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (25 frames)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (45 frames)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#82     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#83     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:20)
#84     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#85     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#86     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#87     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962:59)
#88     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#89     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#90     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#91     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#92     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#94     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#95     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#97     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#98     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1935:12)
#99     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1881:20)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#110    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#116    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#118    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#120    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#121    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#122    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#123    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#125    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#126    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#128    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#129    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#130    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#132    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#133    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#134    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#135    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#136    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#137    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#138    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#139    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#140    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#141    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#142    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#146    _invoke (dart:ui/hooks.dart:150:10)
#147    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#148    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
```

</details>

**Comment by daohoangson** [comment]
Hmm, can you replace these lines:

```dart
    TextStyle textStyle = FwfhTextStyle.from(
      TextStyle(
        fontFamily: 'FuturaBT',
        fontSize: fontSize,
        color: (getColor == null ? theme.textColor : getColor!(theme, element)) ?? theme.textColor,
      ),
    );
```

with these:

```dart
    TextStyle textStyle = TextStyle(
      fontFamily: 'FuturaBT',
      fontSize: fontSize,
      color: (getColor == null ? theme.textColor : getColor!(theme, element)) ?? theme.textColor,
    );
```

**Comment by Skyost** [comment]
@daohoangson Sorry for the delay ! Will try asap.

**Comment by daohoangson** [comment]
It works?

**Comment by Skyost** [comment]
@daohoangson Can confirm it's working now. Thanks !
